### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by calvinmetcalf** [kevinAlbs/Base122#1]
A license (or since this is a utility type thing a notice of public domain status) would make this far more useful. 

That write up was great BTW

**Comment by kevinAlbs** [comment]
@calvinmetcalf Thanks for bringing this up, I added an MIT license with [this commit](https://github.com/kevinAlbs/Base122/commit/d30d33dfd258a2ff1ca2341d535424b9e0233b50)

And thank you for the kind words!
