### ISSUE TITLE
Malformed byte sequences?

### ISSUE THREAD

**Issue by ernstmoritzhahn** [kevinAlbs/Base122#4]
When I download the file from
https://raw.githubusercontent.com/kevinAlbs/Base122/master/casestudy/out/10-base122.html
and upload it to
https://www.freeformatter.com/html-validator.html
results in a number of "Malformed byte sequence" errors. When using
https://validator.w3.org/
a file upload results in an internal server error (which is a problem on their side), but using the option "Validate by direct input" leads to similar problems. So, I wonder, is there something wrong with these markup validators or does the base122 implementation indeed use byte sequences which are not valid UTF-8?

**Comment by kevinAlbs** [comment]
It is valid utf8, but it is not standards compliant HTML (see the comments in #3). This is another important reason not to use this encoding in HTML.

And to double check that it is valid utf8, I used [this package](https://www.npmjs.com/package/utf-8-validate) and the following:
```javascript
const fs = require('fs');
const isValidUTF8 = require('utf-8-validate');
const buf = fs.readFileSync('./10-base122.html')
console.log(isValidUTF8(buf)); // true
```

Heh, it's interesting that w3 gives an internal server error. That file having a `<meta charset="utf-8">` but it seems like it's an issue with w3's encoding detection. If you select the option for utf-8 encoding it goes through and gives the right error messages.
